imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata/formatter.yml }
    - { resource: sonata/admin.yml }
    - { resource: sonata/block.yml }
    - { resource: sonata/media.yml }
    - { resource: sonata/ckeditor.yml }
    - { resource: fos/user.yml }
    - { resource: fos/rest.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru
    default_locale: "%locale%"

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'SonataFormatterBundle:Form:formatter.html.twig'
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - 'DomstorTemplateBundle::captcha.html.twig'

assetic:
    debug:          "%kernel.debug%"
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~    
        scssphp:
            apply_to: "\\.scss$"
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        default_table_options:
            charset:      utf8
            collate:      utf8_unicode_ci
            engine:       InnoDB
        types:
            json: Sonata\Doctrine\Types\JsonType
        options:
            1002: "SET NAMES UTF8"

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                auto_mapping: true
        resolve_target_entities:
            Sonata\MediaBundle\Model\MediaInterface: AppBundle\Entity\Media

# Swiftmailer Configuration
swiftmailer:
    default_mailer: default
    mailers:
            default:
                transport: %mailer_transport%
                host:      %mailer_host%
                username:  %mailer_user%
                password:  %mailer_password%
                spool:     { type: memory }
                logging:    %kernel.debug%

jms_serializer:
  metadata:
    auto_detection: true

knp_paginator:
    page_range: 12                     
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: 'AppBundle:Pagination:pagination.html.twig'
        
domstor_template:
    domstorlib:
        realtyicons:
            org_id: 13
            location_id: 2004
            template: 'DomstorTemplateBundle:Block:realtyicons.html.twig'
            cache_dir: '%kernel.cache_dir%'
            cache_type: 'file'
            cache_time: 86400
    mailer:
        request: 
            service: 'default'
            to: '%mailer_request_recipients%'
            from: '%mailer_request_from%'
            subject: '%mailer_request_subject%'
            email_template: 'DomstorTemplateBundle:Email:email_request.html.twig'