app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
app_static_pages:
    resource: '@AppBundle/Resources/config/static_routing.yml'

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
    
domstor_template:
    resource: '@DomstorTemplateBundle/Resources/config/routing.yml'
    prefix: /
    
domstor_template_api:
    type: rest
    prefix: /api
    resource: '@DomstorTemplateBundle/Resources/config/api_routing.yml'
        
#domstor_template_annotation:
#    resource: '@DomstorTemplateBundle/Controller/'
#    type: annotation
#    

#
#domstor_template_static:
#    resource: '@DomstorTemplateBundle/Resources/config/static_routing.yml'
#    prefix: /