app_static_about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    AppBundle:Static:about.html.twig
        
app_static_contact:
    path: /contact
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    AppBundle:Static:contact.html.twig